#!/bin/bash

function month_to_number() {
        stringZ="01"
  case "$1" in
        "Jan") stringZ="01";;
        "Feb") stringZ="02";;
        "Mar") stringZ="03";;
        "Apr") stringZ="04";;
        "May") stringZ="05";;
        "Jun") stringZ="06";;
        "Jul") stringZ="07";;
        "Aug") stringZ="08";;
        "Sep") stringZ="09";;
        "Oct") stringZ="10";;
        "Nov") stringZ="11";;
        "Dec") stringZ="12";;
        *) stringZ="01";;
  esac
echo "$stringZ"
} #end month_to_number


function number_to_month() {
        input="$1"
        stringZ="Jan"
        if [ ${#input} -lt 2 ] && [ $input -lt 10 ]; then
                input="0$input"
        fi
  case "$input" in
        "01") stringZ="Jan";;
        "02") stringZ="Feb";;
        "03") stringZ="Mar";;
        "04") stringZ="Apr";;
        "05") stringZ="May";;
        "06") stringZ="Jun";;
        "07") stringZ="Jul";;
        "08") stringZ="Aug";;
        "09") stringZ="Sep";;
        "10") stringZ="Oct";;
        "11") stringZ="Nov";;
        "12") stringZ="Dec";;
        *) stringZ="Jan";;
  esac
echo "$stringZ"
} #end number_to_month

