#!/bin/bash

## LOCAL BASH SETTINGS ##
 export profileDir="$HOME/.skinforhair_settings"

#Grab variables
 #export pVAR=$profileDir/var
  #for f in $pVAR/*;do source $f; done
 export pBIN=$profileDir/bin
 export pLIB=$profileDir/lib
 #active should be a symlink to the local machine
 export lBIN=$profileDir/bin/active
 export pENV=$profileDir/env
 
#add Aliases
 export pALS=$profileDir/aliases/global
 #active should be a symlink to the local machine
 export lALS=$profileDir/aliases/active
  for f in $pALS/*;do if [ ! -d $f ]; then source $f;fi;done
  for f in $lALS/*;do if [ ! -d $f ]; then source $f;fi;done

#Run custom login scripts
 if [ -d "$pENV/active/startup_scripts/$(hostname)" ]; then
   for f in $pENV/active/startup_scripts/$(hostname)/*;do if [ ! -d $f ]; then `$f`;fi;done
 fi

#set up color command prompt
 source $pENV/color_command_prompt
 
 #set PATH
 PATH=$PATH:$lBIN:$pBIN/global:$pBIN/global/networking:$pBIN/global/password:$pBIN/global/git
